var novelQuotes = [
    { quotes: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", book: "Pride and Prejudice",author: "Jane Austen" },
    { quotes: "Whatever our souls are made of, his and mine are the same.", book: "Wuthering Heights", author:"Emily Brontë" },
    { quotes: "All animals are equal, but some animals are more equal than others.", book: "Animal Farm",author:"George Orwell" },
    { quotes: "It was the best of times, it was the worst of times…", book: "A Tale of Two Cities",author:"Charles Dickens" },
    { quotes: "So we beat on, boats against the current, borne back ceaselessly into the past.", book: "The Great Gatsby" ,author:"F. Scott Fitzgerald" },
    { quotes: "To the well-organized mind, death is but the next great adventure.", book: "Harry Potter and the Sorcerer’s Stone", author:"J.K. Rowling" },
    { quotes: "The creatures outside looked from pig to man, and from man to pig, and from pig to man again…", book: "Animal Farm",author:"George Orwell" },
    { quotes: "There is no greater agony than bearing an untold story inside you.", book: "I Know Why the Caged Bird Sings",author:"Maya Angelou" },
    { quotes: "After all, tomorrow is another day.", book: "Gone with the Wind",author:"Margaret Mitchell" },
    { quotes: "Stay gold, Ponyboy, stay gold.", book: "The Outsiders",author:"S.E. Hinton" },
    { quotes: "Hell is other people.", book: "No Exit",author:"Jean-Paul Sartre" },
    { quotes: "It’s only after we’ve lost everything that we’re free to do anything.", book: "Fight Club",author:"Chuck Palahniuk" },
    { quotes: "Man is not made for defeat. A man can be destroyed but not defeated.", book: "The Old Man and the Sea",author:"Ernest Hemingway" },
    { quotes: "Who controls the past controls the future. Who controls the present controls the past.", book: "1984",author:"George Orwell" },
    { quotes: "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.", book: "The Stranger",author:"Albert Camus" },
    { quotes: "We are all fools in love.", book: "Pride and Prejudice",author:"Jane Austen" },
    { quotes: "Time, which sees all things, has found you out.", book: "Oedipus Rex",author:"Sophocles" },
    { quotes: "It's a sin to kill a mockingbird.", book: "To Kill a Mockingbird",author:"Harper Lee" },
    { quotes: "It’s strange because sometimes, I read a book, and I think I am the people in the book.", book: "The Perks of Being a Wallflower",author:"Stephen Chbosky" },
    { quotes: "What is essential is invisible to the eye.", book: "The Little Prince",author:"Antoine de Saint-Exupéry" },
    { quotes: "It's no use going back to yesterday, because I was a different person then.", book: "Alice’s Adventures in Wonderland",author:"Lewis Carroll" },
    { quotes: "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.", book: "The Stranger",author:"Albert Camus" },
    { quotes: "We accept the love we think we deserve.", book: "The Perks of Being a Wallflower",author:"Stephen Chbosky" },
    { quotes: "A reader lives a thousand lives before he dies. The man who never reads lives only one.", book: "A Dance with Dragons",author:"George R.R. Martin" },
    { quotes: "When someone leaves, it's because someone else is about to arrive.", book: "The Zahir",author:"Paulo Coelho" },
    { quotes: "When you play the game of thrones, you win or you die. There is no middle ground.", book: "A game of thrones",author:"George R. R. Martin"},
    { quotes: "Memories warm you up from the inside. But they also tear you apart.", book: "Kafka on the Shore",author: "Haruki Murakami" },
    { quotes: "There are darknesses in life and there are lights, and you are one of the lights.", book: "Dracula",author:"Bram Stoker" },
    { quotes: "I took a deep breath and listened to the old brag of my heart: I am, I am, I am.", book: "The Bell Jar",author:"Sylvia Plath" },
    { quotes: "You never really understand a person until you consider things from his point of view.", book: "To Kill a Mockingbird",author:"Harper Lee" },
    { quotes: "Kill the boy, and let the man be born", book: "A Game of Thrones",author:"George R.R. Martin" },
    { quotes: "Even the darkest night will end and the sun will rise.", book: "Les Misérables",author:"Victor Hugo" },
    { quotes: "It's no use going back to yesterday, because I was a different person then.", book: "Alice’s Adventures in Wonderland",author:"Lewis Carroll" },
    { quotes: "I am haunted by humans.", book: "The Book Thief",author:"Markus Zusak" },
    { quotes: "You forget what you want to remember, and you remember what you want to forget.", book: "The Road",author:"Cormac McCarthy" },
    { quotes: "Monsters are real, and ghosts are real too. They live inside us, and sometimes, they win.", book: "The Shining",author:"Stephen King" },
    { quotes: "He who has a why to live can bear almost any how.", book: "Man’s Search for Meaning",author:"Viktor E. Frankl" },
    { quotes: "A reader lives a thousand lives before he dies.", book: "A Dance with Dragons",author:"George R.R. Martin" },
    { quotes: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", book: "Harry Potter and the Prisoner of Azkaban",author:"J.K. Rowling" },
    { quotes: "There is some good in this world, and it’s worth fighting for.", book: "The Two Towers, J.R.R. Tolkien" },
    { quotes: "It does not do to dwell on dreams and forget to live.", book: "Harry Potter and the Sorcerer’s Stone",author:"J.K. Rowling" },
    { quotes: "Not all those who wander are lost.", book: "The Fellowship of the Ring",author:"J.R.R. Tolkien" },
    { quotes: "Until I feared I would lose it, I never loved to read. One does not love breathing.", book: "To Kill a Mockingbird",author:"Harper Lee" },
    { quotes: "The only thing that you absolutely have to know, is the location of the library.", book: "Matilda",author:"Roald Dahl" },
    { quotes: "If you want to know what a man’s like, take a good look at how he treats his inferiors, not his equals.", book: "Harry Potter and the Goblet of Fire",author:"J.K. Rowling" },
    { quotes: "Memories warm you up from the inside. But they also tear you apart.", book: "Kafka on the Shore",author:"Haruki Murakami" },
    { quotes: "It’s the possibility of having a dream come true that makes life interesting.", book: "The Alchemist",author:"Paulo Coelho" },
    { quotes: "I wish it need not have happened in my time,” said Frodo. “So do I,” said Gandalf…", book: "The Fellowship of the Ring",author:"J.R.R. Tolkien" },
    { quotes: "People generally see what they look for, and hear what they listen for.", book: "To Kill a Mockingbird",author:"Harper Lee" },
    { quotes: "There’s no place like home.", book: "The Wonderful Wizard of Oz",author:"L. Frank Baum" }
];
function generateQuote() {
    var random = Math.floor(Math.random() * novelQuotes.length);
    document.getElementById("quote").innerHTML = `"${novelQuotes[random].quotes}"`;
    document.getElementById("book").innerHTML = `${novelQuotes[random].book}`;
    document.getElementById("author").innerHTML = `${novelQuotes[random].author}`;
}